language: cpp
compiler: gcc

sudo: required
dist: trusty

addons:
  apt:
    packages:
      - libboost-dev

install: chmod +x build/prepare_platform.sh && build/prepare_platform.sh
script: cd gdal-2.0.1 && ./configure && make
